"""AI package for git-acp."""

from git_acp.ai.client import AIClient
from git_acp.ai.commit_prompts_advanced import (
    ADVANCED_COMMIT_SYSTEM_PROMPT,
)
from git_acp.ai.commit_prompts_simple import (
    SIMPLE_COMMIT_SYSTEM_PROMPT,
)
from git_acp.ai.pr_prompts_advanced import (
    ADVANCED_PR_TITLE_SYSTEM_PROMPT,
    ADVANCED_PR_TITLE_USER_PROMPT,
    ADVANCED_PR_SUMMARY_SYSTEM_PROMPT,
    ADVANCED_PR_SUMMARY_USER_PROMPT,
    ADVANCED_CODE_CHANGES_SYSTEM_PROMPT,
    ADVANCED_CODE_CHANGES_USER_PROMPT,
    ADVANCED_REASON_CHANGES_SYSTEM_PROMPT,
    ADVANCED_REASON_CHANGES_USER_PROMPT,
    ADVANCED_TEST_PLAN_SYSTEM_PROMPT,
    ADVANCED_TEST_PLAN_USER_PROMPT,
    ADVANCED_ADDITIONAL_NOTES_SYSTEM_PROMPT,
    ADVANCED_ADDITIONAL_NOTES_USER_PROMPT,
    PR_REVIEW_SYSTEM_PROMPT,
    PR_REVIEW_USER_PROMPT,
)

from git_acp.ai.pr_prompts_simple import (
    SIMPLE_PR_SYSTEM_PROMPT,
    SIMPLE_PR_USER_PROMPT,
    SIMPLE_TITLE_EXTRACTION_SYSTEM_PROMPT,
    SIMPLE_TITLE_EXTRACTION_USER_PROMPT,
)
from git_acp.commit.generation import generate_commit_message

__all__ = [
    "AIClient",
    "generate_commit_message",
    "ADVANCED_COMMIT_SYSTEM_PROMPT",
    "SIMPLE_COMMIT_SYSTEM_PROMPT",
    "ADVANCED_PR_TITLE_SYSTEM_PROMPT",
    "ADVANCED_PR_TITLE_USER_PROMPT",
    "ADVANCED_PR_SUMMARY_SYSTEM_PROMPT",
    "ADVANCED_PR_SUMMARY_USER_PROMPT",
    "ADVANCED_CODE_CHANGES_SYSTEM_PROMPT",
    "ADVANCED_CODE_CHANGES_USER_PROMPT",
    "ADVANCED_REASON_CHANGES_SYSTEM_PROMPT",
    "ADVANCED_REASON_CHANGES_USER_PROMPT",
    "ADVANCED_TEST_PLAN_SYSTEM_PROMPT",
    "ADVANCED_TEST_PLAN_USER_PROMPT",
    "ADVANCED_ADDITIONAL_NOTES_SYSTEM_PROMPT",
    "ADVANCED_ADDITIONAL_NOTES_USER_PROMPT",
    "SIMPLE_PR_SYSTEM_PROMPT",
    "SIMPLE_PR_USER_PROMPT",
    "SIMPLE_TITLE_EXTRACTION_SYSTEM_PROMPT",
    "SIMPLE_TITLE_EXTRACTION_USER_PROMPT",
    "PR_REVIEW_SYSTEM_PROMPT",
    "PR_REVIEW_USER_PROMPT",
]
